adds book now section
VAClaimsInsider/tmda-website pull request #9
Opened 2023-08-14 21:38 UTC by timtran007

Adds the Book Now Section with image - and made the section mobile friendly as well.

2023-08-29 15:05 UTC, theleewise requested changes

2023-08-29 15:05 UTC, theleewise commented on pages/services.js
> +								height: '100%',
Remove these so image will line up with top of booking and won't move around as booking widget grow and shrinks

2023-08-29 15:05 UTC, theleewise commented on pages/services.js
> +									overflow: {xs:'none', md:'auto'},
Remove `xs` properties.

These are unnecessary since it works by going up from mobile first, your styles don't apply until the `md` breakpoint so there is nothing to reset or override.

2023-08-30 13:37 UTC, timtran007 commented
Hey @theleewise! Sorry didn't realize this had comments in them yesterday. I resolved them :)

2023-08-30 15:24 UTC, merged